### ISSUE TITLE
Standardize C builds using Makefiles and include instructions for local builds

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry-holding/device-bluetooth-c#10]
To be honest I thought about piggybacking off #1 but there is some nuance to create a new issue for it. I also pasted this issue for device-opcua-c as well: https://github.com/edgexfoundry-holding/device-opcua-c/issues/25

In the main repository we have the Go repositories using Makefiles to standardize their build processes on the targets; `build`, `test`, `docker` and `clean`. So far the C repositories are not using this same pattern and it is slowing us down for the build infrastructure and releases. 

Example of the Go Makefile: https://github.com/edgexfoundry/device-sdk-go/blob/master/Makefile

I'm not seeing the ability to hook Codecov into the the C builds as result. To use our current process we need a coverage report to be created using `gcov`. This is shown in the Codecov example for C here: https://github.com/codecov/example-c

The dependency on a VERSION file should be removed. We are removing that requirement from the build infrastructure in Geneva and keeping it will hinder us moving forward.

**Comment by FraserG01** [comment]
completed: edgexfoundry-holding/device-bluetooth-c/pull/11
fixed for ble change: edgexfoundry-holding/device-bluetooth-c/pull/18
