### ISSUE TITLE
build_dep.sh clones a CBOR repo w/out specifying a release tag or commit

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry-holding/device-bluetooth-c#3]
The file build_deps.sh clones a CBOR git repository in order to build the C SDK.  If this CBOR core is a build dependency of the C SDK, then I would expect it to be handled by the C SDK build, not a device service. I also would expect a release tag or commit to be specified. Without such, it'd be easy for upstream to commit a change which breaks the SDK and/or this device service.

I checked and there have been [seven releases](https://github.com/PJK/libcbor/releases) of this CBOR project, so this shouldn't be a big change. That said, I also wonder why this dependency isn't handled via an OS devel package?

**Comment by FraserG01** [comment]
completed: edgexfoundry-holding/device-bluetooth-c/pull/8
