### ISSUE TITLE
Please clarify inclusion of attribution.txt

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry-holding/device-bluetooth-c#5]
I'm not super familiar with CMake, but it looks to me like this device service is still using dynamic libraries vs. statically linking against the SDK and libdbus. If so, then there's no need to add a top-level [attribution.txt](https://github.com/edgexfoundry-holding/device-bluetooth-c/blob/master/attribution.txt) (which is typically only needed for static linking), instead you should copy the copyright and/or license files from the Alpine dbus package into your container.  These are usually copied to /usr/share/doc/<package-name>.

**Comment by FraserG01** [comment]
completed: edgexfoundry-holding/device-bluetooth-c/pull/9
